### ISSUE TITLE
Not support go module !!

### ISSUE THREAD

**Issue by up1** [tspn/rate-limit#1]
Not support go module !!
please update 
* package of project/module to github.com/tspn/rate-limit ?
* tag/release with semantic versioning ?

**Comment by tnuanchuay** [comment]
hola, un momento senor

**Comment by tnuanchuay** [comment]
#2 
@up1 Could you kindly review this pr please ?

**Comment by tnuanchuay** [comment]
What is the go standard to do tag/release ?
Put in to `go.mod` like
```
module github.com/tspn/rate-limit/v1.0.0
```

or use git tag

**Comment by up1** [comment]
> What is the go standard to do tag/release ?
> Put in to `go.mod` like
> 
> ```
> module github.com/tspn/rate-limit/v1.0.0
> ```
> 
> or use git tag

Use git tag

**Comment by tnuanchuay** [comment]
created tag 1.0.0
